---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible
  vars:
  tasks:
  - name: Add AuthorizedKeysCommand directive to /etc/ssh/sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '.*AuthorizedKeysCommand.*'
      line: 'AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys'

  - name: Add AuthorizedKeysCommandUser directive to /etc/ssh/sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '.*AuthorizedKeysCommandUser.*'
      line: 'AuthorizedKeysCommandUser nobody'
    notify: Reload sshd config

  - name: Enable public key authentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '.*PubkeyAuthentication.*'
      line: 'PubkeyAuthentication yes'
      validate: 'sshd -tf %s'
    notify: Reload sshd config

  handlers:
  - name: Reload sshd config
    systemd:
      name: sshd
      state: reloaded
      daemon-reload: yes