---
<<<<<<< HEAD
<<<<<<< HEAD
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible
  vars:
  tasks:
#  - name: Join as CentOS 7
#    import_tasks: ad_join_centos7.yml
#    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
=======
=======
>>>>>>> parent of 90d556f... Finishing main AD join playbook
- tasks:
  - name: Join as CentOS 7
    include: ad_join_centos7.yml
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
>>>>>>> parent of 90d556f... Finishing main AD join playbook

  - name: Join as Ubuntu 16
    import_playbook: ad_join_ubuntu16.yml
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16")