---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible
  vars:
  tasks:
  - name: Join as CentOS 7
    include_tasks: ad_join_centos7_TASKS.yml
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

  - name: Join as Ubuntu 16
    include_tasks: ad_join_ubuntu16_TASKS.yml
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16")