# CentOS 7 Active Directory join using realmd

<<<<<<< HEAD
=======
---
- hosts: all
  become: yes
  become_method: sudo
  vars:

>>>>>>> parent of 90d556f... Finishing main AD join playbook
  tasks:
  - name: Installation prerequisites (EPEL)
    yum:
      name: epel-release
      state: latest
      update_cache: yes

  - name: Install required packages
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
    - realmd
    - sssd
    - chrony
    - krb5-workstation
    - samba-common
    - samba-common-tools
    - oddjob
    - oddjob-mkhomedir
    - python-pip

# Install pip and related required packages

  - name: Upgrade pip to latest version
    command: /bin/pip install --upgrade pip

  - name: Install pip setuptools
    command: /bin/pip install setuptools

  - name: Install python pexpect package via pip
    command: /bin/pip install pexpect

# Configuring chrony to use domain controllers at time servers

  - name: Ensure that chronyd is installed
    yum:
      name: chrony
      state: present

# Comments out any lines starting with "server" and containing "centos", ending with "iburst".
# Why sed? Using sed was easier for me than trying to figure out how to get the backrefs to work in the
# replace module.

  - name: Comment out default CentOS pool
    command: /bin/sed -i '/^server.*centos.*iburst$/s/^/#\ /g' /etc/chrony.conf

  - name: Add dc02.corp.tanium.com to chrony.conf
    lineinfile:
      path: /etc/chrony.conf
      line: 'server dc02.corp.tanium.com iburst'
    notify: Reload chrony

  - name: Add dc01.corp.taniun.com to chrony.conf
    lineinfile:
      path: /etc/chrony.conf
      line: 'server dc01.corp.tanium.com iburst'
    notify: Reload chrony

  - name: Join the domain
    expect:
      command: /sbin/realm join -U {{ adm_user }}@corp.tanium.com corp.tanium.com
      responses:
        '^Password for.*:': "{{ adm_password }}"
      timeout: 15
    no_log: true         # uncomment this when in production -- obfuscates the password in logs


# Configuration file copy for Kerberos and SSSD

  - name: Install sane krb5.conf file
    template:
      src: krb5.conf
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0600

  - name: Install sane sssd.conf file
    template:
      src: sssd.conf
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600
    notify: Restart SSSD

  handlers:
    - name: Restart SSSD
      service:
        name: sssd
        state: restarted

    - name: Reload chrony
      systemd:
        name: chrony
        state: reloaded