---
- hosts: all
  become: yes
  become_method: sudo
  vars:
  tasks:
  - name: Copy MOTD to destination system(s)
    copy:
      src: ~/AnsiblePlaybooks/Banners/motd
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
